{% set name = "simple-pid" %}
{% set version = "0.2.4" %}
{% set sha256 = "441150075c846460acd38eeb232bab1ac75194f851237f0459307217e4a57525" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simple_pid
  # TODO: Uncomments these lines to test the resource files are included in the
  # PyPI sdist (https://github.com/m-lundberg/simple-pid/pull/31).
  # commands:
  #   - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("simple_pid", "PID.pyi"))'
  #   - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("simple_pid", "py.typed"))'

about:
  home: https://github.com/m-lundberg/simple-pid
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A simple, easy to use PID controller
  dev_url: https://github.com/m-lundberg/simple-pid
  doc_url: https://simple-pid.readthedocs.io
